# Generated by Django 3.1.5 on 2021-02-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='title',
            field=models.CharField(default='Entry: 2021-02-03 12:53:27.660195', max_length=150),
        ),
    ]
