# Generated by Django 3.1.5 on 2021-02-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210203_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
